name: list-repo

on:
  push:
    branches:
      - main

jobs:
  count_lines:
    name: Count lines in repository
      runs-on: ubuntu-latest
      steps:
        run: python pip install pygount
        run: pygount --format=summary ./Generation



#jobs:
#  list-repo-files:
#    name: List files in repository
#    runs-on: ubuntu-latest
#    steps:
#      - name: checkout-repo
#        uses: actions/checkout@v2
#      - name: list-dir
#        run: ls -laR # Recursively list directory contents
