name: list-repo

on:
  push:
    branches:
      - main

jobs:
  count_lines:
    name: Count lines in repository
    runs-on: ubuntu-latest
    steps:
      - name: checkout-repo
        uses: actions/checkout@v2
      - name: Python
        uses: actions/setup-python@v3
        with:
          python_version: "3.10"
      - name: Install Pygount
        run: |
          python -m pip install --upgrade pip
          pip install pygount
      - name: Run count
        run: pygount --format=summary ./Project



#jobs:
#  list-repo-files:
#    name: List files in repository
#    runs-on: ubuntu-latest
#    steps:
#      - name: checkout-repo
#        uses: actions/checkout@v2
#      - name: list-dir
#        run: ls -laR # Recursively list directory contents
